services:
  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php
      - mailhog

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/
    command: >
      sh -c "
        php artisan storage:link &&
        php-fpm
      "

  mysql:
    image: arm64v8/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: furima_db
      MYSQL_USER: furima_user
      MYSQL_PASSWORD: furima_pass
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: arm64v8/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=furima_user
      - PMA_PASSWORD=furima_pass
    depends_on:
      - mysql
    ports:
      - 8080:80

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP受信ポート
      - "8025:8025"  # Web UI（ブラウザでアクセス可能）
